# ============================================================
# Simulasi ConfigMap OCP: app-config
# Ini merepresentasikan konfigurasi aplikasi utama
# ============================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: demo-uat
  labels:
    app: myapp
    env: uat
    sync: enabled
data:
  APP_ENV: "uat"
  APP_PORT: "8080"
  APP_LOG_LEVEL: "INFO"
  APP_MAX_CONNECTIONS: "263"
  FEATURE_FLAG_NEW_UI: "false"
  FEATURE_FLAG_DARK_MODE: "true"
integration:
  scm:
    baseURL: "https://localhost:8080/scm/api/v1"